import type { Permission, TaskKind } from "@open-project-council/core";

export type WorkspaceLocale = "zh" | "en";

export type TaskTemplate = {
  id: string;
  kind: TaskKind;
  title: Record<WorkspaceLocale, string>;
  summary: Record<WorkspaceLocale, string>;
  goal: Record<WorkspaceLocale, string>;
  acceptanceCriteria: Record<WorkspaceLocale, string[]>;
  context: Record<WorkspaceLocale, string[]>;
  allowedTools: string[];
  budgetUsd: number;
  requiredPermissions: Permission[];
};

export const taskTemplates: TaskTemplate[] = [
  {
    id: "math-proof",
    kind: "math",
    title: { zh: "证明边界条件与反例", en: "Prove boundary cases and counterexamples" },
    summary: { zh: "双求解器与独立验证", en: "Two solvers with independent verification" },
    goal: { zh: "给出可复核的推导，明确假设、边界条件和可能的反例。", en: "Produce a reviewable derivation with explicit assumptions, boundary cases, and counterexamples." },
    acceptanceCriteria: {
      zh: ["定义、假设和结论彼此一致", "推导可逐步复核", "列出未解决的边界或反例"],
      en: ["Definitions, assumptions, and conclusions are consistent", "The derivation is reviewable step by step", "Unresolved boundary cases or counterexamples are listed"],
    },
    context: { zh: ["待验证的命题或公式", "已知条件与适用范围"], en: ["Statement or formula to verify", "Known conditions and applicability range"] },
    allowedTools: [],
    budgetUsd: 3,
    requiredPermissions: ["read"],
  },
  {
    id: "math-optimization",
    kind: "math",
    title: { zh: "求解约束优化与敏感性", en: "Solve constrained optimization and sensitivity" },
    summary: { zh: "建模、求解与条件检验", en: "Model, solve, and check conditions" },
    goal: { zh: "建立可复核的优化模型，给出求解方法并分析关键参数变化对结论的影响。", en: "Build a reviewable optimization model, solve it, and analyze sensitivity to key parameters." },
    acceptanceCriteria: {
      zh: ["变量、目标函数和约束定义完整", "可行性与最优性条件被检查", "列出参数敏感性和数值限制"],
      en: ["Variables, objective, and constraints are complete", "Feasibility and optimality conditions are checked", "Sensitivity and numerical limits are recorded"],
    },
    context: { zh: ["目标函数与约束", "参数范围和单位"], en: ["Objective and constraints", "Parameter ranges and units"] },
    allowedTools: ["计算"],
    budgetUsd: 4,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "math-algorithm-analysis",
    kind: "math",
    title: { zh: "分析算法正确性与复杂度", en: "Analyze algorithm correctness and complexity" },
    summary: { zh: "不变量、边界与渐近分析", en: "Invariants, boundaries, and asymptotics" },
    goal: { zh: "为算法给出正确性论证、时间与空间复杂度，并检查极端输入和失败模式。", en: "Provide a correctness argument, time and space complexity, and inspect extreme inputs and failure modes." },
    acceptanceCriteria: {
      zh: ["关键循环或递归不变量被明确说明", "复杂度假设和推导可复核", "边界输入与反例已检查"],
      en: ["Key loop or recursion invariants are explicit", "Complexity assumptions and derivation are reviewable", "Boundary inputs and counterexamples are checked"],
    },
    context: { zh: ["伪代码或现有实现", "输入规模与性能目标"], en: ["Pseudocode or existing implementation", "Input scale and performance target"] },
    allowedTools: ["终端", "测试"],
    budgetUsd: 4,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "coding-delivery",
    kind: "coding",
    title: { zh: "交付一个可验证的软件功能", en: "Deliver a verifiable software feature" },
    summary: { zh: "架构、实现与测试审查", en: "Architecture, implementation, and test review" },
    goal: { zh: "实现一个边界清晰的功能，保留设计取舍并用自动化验证关键行为。", en: "Implement a well-bounded feature, record design trade-offs, and verify critical behavior automatically." },
    acceptanceCriteria: {
      zh: ["实现覆盖声明的验收条件", "测试或类型检查覆盖关键风险", "未解决的安全或发布风险被明确记录"],
      en: ["The implementation covers the declared acceptance criteria", "Tests or type checks cover critical risks", "Unresolved security or release risks are recorded explicitly"],
    },
    context: { zh: ["现有代码与约束", "接口、性能或兼容性要求"], en: ["Existing code and constraints", "Interface, performance, or compatibility requirements"] },
    allowedTools: ["终端", "测试"],
    budgetUsd: 6,
    requiredPermissions: ["read", "write", "execute"],
  },
  {
    id: "coding-debug-regression",
    kind: "coding",
    title: { zh: "定位并修复回归问题", en: "Diagnose and fix a regression" },
    summary: { zh: "复现、根因与回归测试", en: "Reproduce, find root cause, and regress" },
    goal: { zh: "稳定复现问题，定位最小根因，实施修复并用针对性测试防止回归。", en: "Reproduce the issue reliably, find the minimal root cause, fix it, and prevent recurrence with focused tests." },
    acceptanceCriteria: {
      zh: ["问题有可重复的复现步骤或测试", "修复解释了根因而非只掩盖现象", "新增测试在修复前失败、修复后通过"],
      en: ["The issue has repeatable reproduction steps or a test", "The fix explains the root cause rather than masking symptoms", "A new test fails before and passes after the fix"],
    },
    context: { zh: ["错误现象与复现条件", "近期变更、日志或堆栈"], en: ["Observed failure and reproduction conditions", "Recent changes, logs, or stack trace"] },
    allowedTools: ["终端", "测试", "日志"],
    budgetUsd: 5,
    requiredPermissions: ["read", "write", "execute"],
  },
  {
    id: "coding-refactor-migration",
    kind: "coding",
    title: { zh: "重构模块并安全迁移", en: "Refactor a module and migrate safely" },
    summary: { zh: "边界、兼容与验证", en: "Boundaries, compatibility, and verification" },
    goal: { zh: "改善模块边界或替换旧实现，迁移调用方并以自动化检查维持既有行为。", en: "Improve module boundaries or replace legacy code, migrate callers, and preserve behavior with automated checks." },
    acceptanceCriteria: {
      zh: ["新旧职责边界与迁移范围明确", "调用方完成迁移且无死代码", "兼容性与性能风险有验证或记录"],
      en: ["New boundaries and migration scope are explicit", "Callers are migrated with no dead code left behind", "Compatibility and performance risks are verified or recorded"],
    },
    context: { zh: ["当前模块和调用方", "必须保持的兼容性契约"], en: ["Current module and callers", "Compatibility contracts to retain"] },
    allowedTools: ["终端", "测试"],
    budgetUsd: 7,
    requiredPermissions: ["read", "write", "execute"],
  },
  {
    id: "review-pull-request",
    kind: "code-review",
    title: { zh: "审查改动并给出可执行结论", en: "Review a change set with actionable findings" },
    summary: { zh: "独立审查与风险分级", en: "Independent review and risk ranking" },
    goal: { zh: "对代码改动进行独立审查，按影响排序问题，并只提出可由代码或测试验证的结论。", en: "Review a change set independently, rank issues by impact, and report only findings verifiable in code or tests." },
    acceptanceCriteria: {
      zh: ["每项发现定位到具体行为或代码位置", "区分阻塞问题、风险与建议", "没有问题时明确剩余测试缺口"],
      en: ["Each finding points to a concrete behavior or code location", "Blocking issues, risks, and suggestions are distinct", "Remaining test gaps are explicit when no issue is found"],
    },
    context: { zh: ["待审查的差异", "接口契约与发布约束"], en: ["Change set to review", "Interface contracts and release constraints"] },
    allowedTools: ["代码差异", "测试"],
    budgetUsd: 5,
    requiredPermissions: ["read"],
  },
  {
    id: "review-security",
    kind: "code-review",
    title: { zh: "审查安全边界与敏感数据流", en: "Review security boundaries and sensitive data flow" },
    summary: { zh: "威胁、权限与脱敏审查", en: "Threat, permission, and redaction review" },
    goal: { zh: "检查认证、授权、输入处理、密钥与日志边界，给出可验证的修复优先级。", en: "Inspect authentication, authorization, input handling, secret, and logging boundaries with verifiable remediation priorities." },
    acceptanceCriteria: {
      zh: ["信任边界与攻击面被明确列出", "高风险问题有复现或代码证据", "修复建议符合最小权限原则"],
      en: ["Trust boundaries and attack surface are explicit", "High-risk findings have reproduction or code evidence", "Remediation follows least privilege"],
    },
    context: { zh: ["认证与权限路径", "外部输入、日志和密钥存储"], en: ["Authentication and permission paths", "External input, logs, and secret storage"] },
    allowedTools: ["代码差异", "依赖审查", "测试"],
    budgetUsd: 6,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "security-threat-model",
    kind: "security-audit",
    title: { zh: "建立威胁模型并排序修复", en: "Build a threat model and prioritize remediation" },
    summary: { zh: "资产、攻击路径与缓解措施", en: "Assets, attack paths, and mitigations" },
    goal: { zh: "识别关键资产、信任边界和攻击路径，按可利用性与影响排序风险，并给出最小权限的缓解措施。", en: "Identify critical assets, trust boundaries, and attack paths; rank risks by exploitability and impact; then propose least-privilege mitigations." },
    acceptanceCriteria: {
      zh: ["资产、信任边界和攻击者能力明确", "每个高风险路径有可验证的前提与影响", "修复按优先级、所有者和验证方法排序"],
      en: ["Assets, trust boundaries, and attacker capabilities are explicit", "Each high-risk path has verifiable prerequisites and impact", "Remediation is ranked by priority, owner, and validation method"],
    },
    context: { zh: ["系统架构与数据流", "认证、授权和外部集成"], en: ["System architecture and data flow", "Authentication, authorization, and external integrations"] },
    allowedTools: ["代码差异", "依赖审查", "测试"],
    budgetUsd: 7,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "security-release-gate",
    kind: "security-audit",
    title: { zh: "为发布建立安全准入检查", en: "Create a security release gate" },
    summary: { zh: "变更风险、证据与放行条件", en: "Change risk, evidence, and release criteria" },
    goal: { zh: "对一次发布的身份、数据、依赖和部署变更建立可审计的准入条件，并明确不可放行项。", en: "Define auditable admission criteria for identity, data, dependency, and deployment changes in a release, including explicit no-go conditions." },
    acceptanceCriteria: {
      zh: ["高风险变更与所需证据对应", "密钥、日志和访问控制有明确检查项", "放行、例外和回滚责任人明确"],
      en: ["High-risk changes map to required evidence", "Secrets, logs, and access control have explicit checks", "Approval, exceptions, and rollback owners are explicit"],
    },
    context: { zh: ["本次变更与部署环境", "现有安全控制和回滚方案"], en: ["Current changes and deployment environment", "Existing security controls and rollback plan"] },
    allowedTools: ["代码差异", "依赖审查", "部署记录"],
    budgetUsd: 5,
    requiredPermissions: ["read"],
  },
  {
    id: "research-brief",
    kind: "research",
    title: { zh: "研究问题并形成证据简报", en: "Research a question into an evidence brief" },
    summary: { zh: "检索、反证与来源分级", en: "Search, counterevidence, and source ranking" },
    goal: { zh: "围绕明确问题收集可追溯证据，区分事实、推断与未知项，并主动寻找反证。", en: "Gather traceable evidence around a focused question, separate facts from inference and unknowns, and seek counterevidence." },
    acceptanceCriteria: {
      zh: ["关键结论附有来源或待验证标记", "相互矛盾的证据被保留", "不确定性和后续验证动作明确"],
      en: ["Key claims have sources or a verification marker", "Conflicting evidence is retained", "Uncertainty and next verification actions are explicit"],
    },
    context: { zh: ["研究问题与受众", "时间范围、来源约束和已有材料"], en: ["Research question and audience", "Time range, source constraints, and existing material"] },
    allowedTools: ["浏览器", "检索"],
    budgetUsd: 5,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "research-comparison",
    kind: "research",
    title: { zh: "比较方案并提出决策依据", en: "Compare options with decision evidence" },
    summary: { zh: "标准、证据与保留意见", en: "Criteria, evidence, and dissent" },
    goal: { zh: "按预先声明的标准比较多个方案，保留权衡和无法证实的假设，而非输出虚假的唯一答案。", en: "Compare options against declared criteria, preserve trade-offs and unverified assumptions, and avoid a false single answer." },
    acceptanceCriteria: {
      zh: ["比较标准在结论前定义", "每个方案的证据和缺口可追溯", "推荐结论说明取舍与否决条件"],
      en: ["Comparison criteria are defined before the conclusion", "Evidence and gaps for each option are traceable", "The recommendation explains trade-offs and disqualifiers"],
    },
    context: { zh: ["候选方案", "决策标准、预算和限制"], en: ["Candidate options", "Decision criteria, budget, and constraints"] },
    allowedTools: ["浏览器", "检索"],
    budgetUsd: 5,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "data-analysis-insight",
    kind: "data-analysis",
    title: { zh: "分析数据并交付可复核洞察", en: "Analyze data into reviewable insights" },
    summary: { zh: "口径、分析与统计复核", en: "Definitions, analysis, and statistical review" },
    goal: { zh: "检查数据口径与质量，完成分析并区分观察结果、统计显著性与业务解释。", en: "Inspect data definitions and quality, complete the analysis, and separate observed results, statistical significance, and business interpretation." },
    acceptanceCriteria: {
      zh: ["指标口径、样本和缺失值处理明确", "图表或计算能被复现", "结论不超出数据支持的范围"],
      en: ["Metric definitions, samples, and missing-value handling are explicit", "Charts or computations are reproducible", "Conclusions stay within what the data supports"],
    },
    context: { zh: ["数据集位置或样例", "指标定义和决策问题"], en: ["Dataset location or sample", "Metric definitions and decision question"] },
    allowedTools: ["终端", "计算", "图表"],
    budgetUsd: 6,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "data-analysis-experiment",
    kind: "data-analysis",
    title: { zh: "设计并审查实验分析", en: "Design and review an experiment analysis" },
    summary: { zh: "假设、功效与因果边界", en: "Hypothesis, power, and causal limits" },
    goal: { zh: "为实验或 A/B 测试建立假设、指标、样本量和解释边界，并审查统计与业务风险。", en: "Define hypotheses, metrics, sample size, and interpretation boundaries for an experiment or A/B test, then review statistical and business risks." },
    acceptanceCriteria: {
      zh: ["主指标、护栏指标与停止条件明确", "随机化、样本量和显著性假设可审查", "结论区分相关性与因果性"],
      en: ["Primary, guardrail, and stopping metrics are explicit", "Randomization, sample size, and significance assumptions are reviewable", "Conclusions distinguish correlation from causation"],
    },
    context: { zh: ["实验目标与用户群", "当前样本、指标和实施限制"], en: ["Experiment goal and population", "Current samples, metrics, and delivery constraints"] },
    allowedTools: ["计算", "图表"],
    budgetUsd: 6,
    requiredPermissions: ["read", "execute"],
  },
  {
    id: "product-discovery",
    kind: "product-planning",
    title: { zh: "梳理问题并制定产品验证计划", en: "Frame a problem and plan product validation" },
    summary: { zh: "用户、假设与最小验证", en: "Users, hypotheses, and minimum validation" },
    goal: { zh: "把模糊需求拆成用户问题、待验证假设和最小实验，避免用未验证的方案直接进入开发。", en: "Turn an ambiguous request into user problems, assumptions to test, and minimum experiments before committing to implementation." },
    acceptanceCriteria: {
      zh: ["目标用户、场景和痛点可区分", "假设包含可观察的验证信号", "范围、非目标和下一步决策明确"],
      en: ["Target users, contexts, and pain points are distinguishable", "Hypotheses include observable validation signals", "Scope, non-goals, and the next decision are explicit"],
    },
    context: { zh: ["用户反馈、现有数据或访谈", "业务目标与交付约束"], en: ["User feedback, existing data, or interviews", "Business goals and delivery constraints"] },
    allowedTools: ["研究", "数据分析"],
    budgetUsd: 5,
    requiredPermissions: ["read"],
  },
  {
    id: "product-roadmap-decision",
    kind: "product-planning",
    title: { zh: "比较路线图方案并形成决策记录", en: "Compare roadmap options into a decision record" },
    summary: { zh: "取舍、依赖与否决条件", en: "Trade-offs, dependencies, and no-go conditions" },
    goal: { zh: "按价值、成本、风险和依赖比较候选路线图，输出能被后续团队追溯的决策与保留意见。", en: "Compare roadmap options by value, cost, risk, and dependencies, producing a decision that later teams can trace along with dissent." },
    acceptanceCriteria: {
      zh: ["比较标准在推荐结论前声明", "依赖、容量和机会成本被量化或标记为未知", "推荐包含否决条件与复审时间点"],
      en: ["Comparison criteria precede the recommendation", "Dependencies, capacity, and opportunity cost are quantified or marked unknown", "The recommendation includes disqualifiers and a review date"],
    },
    context: { zh: ["候选项目、预期收益和时间窗口", "团队容量、依赖和风险限制"], en: ["Candidate initiatives, expected value, and time window", "Team capacity, dependencies, and risk constraints"] },
    allowedTools: ["研究", "数据分析"],
    budgetUsd: 6,
    requiredPermissions: ["read"],
  },
  {
    id: "writing-api-guide",
    kind: "technical-writing",
    title: { zh: "编写可执行的 API 集成指南", en: "Write an executable API integration guide" },
    summary: { zh: "契约、示例与失败处理", en: "Contract, examples, and failure handling" },
    goal: { zh: "围绕真实读者任务编写 API 接入文档，覆盖前置条件、最小示例、错误处理和安全边界。", en: "Write API integration documentation around real reader tasks, covering prerequisites, a minimal example, failure handling, and security boundaries." },
    acceptanceCriteria: {
      zh: ["读者能从零完成最小成功请求", "参数、响应和错误示例与契约一致", "不把密钥或私有数据写进示例"],
      en: ["A reader can complete a minimum successful request from scratch", "Parameters, responses, and errors match the contract", "Examples contain no keys or private data"],
    },
    context: { zh: ["API 契约与现有示例", "读者背景和支持边界"], en: ["API contract and existing examples", "Reader background and support boundary"] },
    allowedTools: ["代码差异", "测试"],
    budgetUsd: 4,
    requiredPermissions: ["read"],
  },
  {
    id: "writing-architecture-record",
    kind: "technical-writing",
    title: { zh: "撰写架构决策记录", en: "Write an architecture decision record" },
    summary: { zh: "背景、取舍与后果", en: "Context, trade-offs, and consequences" },
    goal: { zh: "记录一项架构决策的背景、候选方案、证据和后果，使未来维护者能理解为何如此取舍。", en: "Record the context, options, evidence, and consequences of an architecture decision so future maintainers understand the trade-off." },
    acceptanceCriteria: {
      zh: ["问题、约束与决定范围明确", "替代方案及未采纳原因可追溯", "后果、迁移与复审触发条件明确"],
      en: ["Problem, constraints, and decision scope are explicit", "Alternatives and rejection reasons are traceable", "Consequences, migration, and review triggers are clear"],
    },
    context: { zh: ["现有架构与候选方案", "兼容性、性能和运营约束"], en: ["Current architecture and options", "Compatibility, performance, and operational constraints"] },
    allowedTools: ["代码差异", "研究"],
    budgetUsd: 4,
    requiredPermissions: ["read"],
  },
  {
    id: "web-design-review",
    kind: "web-design",
    title: { zh: "设计并审查可实现的网页工作区", en: "Design and review an implementable web workspace" },
    summary: { zh: "需求、前端与截图审查", en: "Requirements, frontend, and screenshot review" },
    goal: { zh: "把用户流程、界面层级和响应式约束落成可实现的网页方案，并用截图审查关键状态。", en: "Turn user flows, hierarchy, and responsive constraints into an implementable web plan, then review key states with screenshots." },
    acceptanceCriteria: {
      zh: ["首屏能识别当前对象与主要动作", "宽屏和窄屏均无重叠或水平溢出", "截图审查保留问题与修复结论"],
      en: ["The first viewport identifies the current object and primary action", "Wide and narrow layouts have no overlap or horizontal overflow", "Screenshot review records issues and fixes"],
    },
    context: { zh: ["目标用户与主要工作流", "现有视觉规范和页面约束"], en: ["Target user and primary workflow", "Existing visual system and page constraints"] },
    allowedTools: ["浏览器", "截图审查"],
    budgetUsd: 5,
    requiredPermissions: ["read", "write"],
  },
  {
    id: "web-responsive-audit",
    kind: "web-design",
    title: { zh: "审查响应式布局与关键状态", en: "Audit responsive layout and critical states" },
    summary: { zh: "视口、交互与截图验证", en: "Viewports, interaction, and screenshot checks" },
    goal: { zh: "检查桌面与移动视口下的布局、交互状态和文本溢出，并将问题转化为可验证的修复项。", en: "Inspect layout, interaction states, and text overflow across desktop and mobile viewports, then turn issues into verifiable fixes." },
    acceptanceCriteria: {
      zh: ["关键宽度下无重叠、截断或横向溢出", "主操作和错误状态可发现", "截图审查覆盖修复前后的关键视图"],
      en: ["Key widths have no overlap, clipping, or horizontal overflow", "Primary actions and error states are discoverable", "Screenshot review covers key views before and after fixes"],
    },
    context: { zh: ["页面地址或组件", "目标设备、断点和已知问题"], en: ["Page URL or component", "Target devices, breakpoints, and known issues"] },
    allowedTools: ["浏览器", "截图审查"],
    budgetUsd: 4,
    requiredPermissions: ["read", "write"],
  },
];

export const defaultTaskTemplate = taskTemplates[1];
